# Generated by Django 5.2.14 on 2026-05-16 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('base_branch', models.CharField(blank=True, max_length=200, null=True)),
                ('requirement', models.TextField(blank=True, null=True)),
                ('acceptance_criteria', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('api', 'REST API'), ('cli', 'Command Line'), ('jira', 'Jira Webhook'), ('trello', 'Trello Webhook'), ('github', 'GitHub Issue')], default='api', max_length=20)),
                ('source_meta', models.JSONField(default=dict)),
                ('dry_run', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='tasks_task_status_8e5503_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('dry_run_complete', 'Dry-run Complete')], default='running', max_length=20)),
                ('timeline', models.JSONField(default=list)),
                ('validation_summary', models.JSONField(default=dict)),
                ('llm_usage', models.JSONField(default=dict)),
                ('diff', models.TextField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='tasks.task')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('duration_ms', models.IntegerField(default=0)),
                ('input_summary', models.TextField(blank=True)),
                ('output_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='tasks.executionreport')),
            ],
            options={
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['agent_name', 'status'], name='tasks_agent_agent_n_7ddeaa_idx')],
            },
        ),
    ]
