# Generated by Django 5.2.14 on 2026-05-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionreport',
            name='workspace_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
