"""PRWriterAgent — assembles PR title and body.

Day 2: pure template (no LLM). Day 3: optional LLM polish for summary.
"""
import re
import time
from decimal import Decimal

import structlog

from apps.tasks.models import ExecutionReport

from .base import AgentInput, AgentOutput, record_agent_run

log = structlog.get_logger(__name__)


class PRWriterInput(AgentInput):
    task_id: str
    title: str
    requirement: str
    acceptance_criteria: list[str]
    changed_files: list[str]
    summary: str
    test_command: str
    test_status: str           # "passed" | "failed" | "skipped"
    test_duration_ms: int
    llm_model: str
    llm_total_tokens: int
    llm_total_cost_usd: float
    retries: int
    trace_id: str


class PRWriterOutput(AgentOutput):
    branch_name: str
    pr_title: str
    pr_body: str
    commit_message: str


class PRWriterAgent:
    name = "pr_writer"

    def __init__(self, llm=None):
        self.llm = llm

    def run(self, input: PRWriterInput, report: ExecutionReport) -> PRWriterOutput:
        started = time.monotonic()

        branch_name = self._make_branch_name(input.task_id, input.title)
        commit_message = f"{input.task_id} {input.title}"
        pr_title = f"{input.task_id} {input.title}"
        pr_body = self._render_body(input)

        output = PRWriterOutput(
            branch_name=branch_name,
            pr_title=pr_title,
            pr_body=pr_body,
            commit_message=commit_message,
        )
        record_agent_run(
            report=report,
            agent_name=self.name,
            model="template",
            started_at=started,
            input_summary=f"task_id={input.task_id} files={input.changed_files}",
            output_summary=f"branch={branch_name} title={pr_title[:200]}",
        )
        log.info("pr_writer.completed", branch=branch_name, title=pr_title)
        return output

    @staticmethod
    def _make_branch_name(task_id: str, title: str) -> str:
        slug = re.sub(r"[^a-zA-Z0-9-]+", "-", title.lower()).strip("-")[:40].strip("-")
        return f"ai-agent/{task_id}-{slug}"

    @staticmethod
    def _render_body(i: PRWriterInput) -> str:
        ac_lines = "\n".join(f"- {c}" for c in i.acceptance_criteria)
        files_lines = "\n".join(f"- {f}" for f in i.changed_files)
        test_emoji = {"passed": "✅", "failed": "❌", "skipped": "⏭"}.get(i.test_status, "❓")
        return f"""> ⚠️ **AI-GENERATED PULL REQUEST**
> This PR was opened automatically by an AI agent.
> Please review carefully before merging.

## Summary
{i.summary}

## Task
{i.task_id}

## Requirement
{i.requirement}

## Acceptance Criteria
{ac_lines}

## Changes
{files_lines}

## Test Result
- Command: `{i.test_command}`
- Status: {test_emoji} {i.test_status}
- Duration: {i.test_duration_ms} ms

## AI Usage
- Model: {i.llm_model}
- Total tokens: {i.llm_total_tokens}
- Estimated cost: ${i.llm_total_cost_usd:.4f}
- Retries: {i.retries}
- Trace ID: `{i.trace_id}`

## Generated By
AI Development Agent (Day 2 build — validation pipeline coming in Day 3)
"""
